### PR TITLE
Fresh merge of master into #244 branch

### PR DESCRIPTION
**Pull request by Freso**
Other than the ALL-LINKS script a lot of code in current #244 branch is very out of date, and git can’t cleanly compare head of master with head of #244 branch. This is a very naive merge using `--strategy-option=theirs` and then pulling in the ALL-LINKS script from #244 branch, so if the branch has any local modifications to anything other than ALL-LINKS, those would be erased here. If not, this merge should make it easier to actually merge the #244 branch once it’s ready.

(I think there might have been some history rewriting since the last master merge? At least, git seems confused when trying to merge normally currently.)

### CODE REVIEW

**Comment by jesus2099** [comment]
Hi @Freso.

The #244/#488 branch is only for mb_ALL-LINKS, so don't worry about the freshness of all the other files. :)
I don't think mb_ALL-LINKS in the branch is late compared to mb-ALL-LINKS in master.
Except for the points that I have to restore its features (cross-charset search with `POST` form, etc.), listed in #488 ticket (quite not clear description).

**Comment by Freso** [comment]
Yeah, but I was trying to see the differences and the amount of changes in everything else made it difficult, so I decided to just make a merge commit… and having done that, I thought I might as well make a PR of it. This will also put things like the EditorConfig file in the working branch for this rewrite, which may prove useful… :)

**Comment by jesus2099** [comment]
I feel so sorry to decline your hard work done for me.

But I already did such a merge from master to 244 branch in the past and I realised it was adding many unrelated file commits in this branch log, making it more confusing.

d47c61581c1eee475a2979c45f487c2b3a9392e9
6ff911d3b32203fcdc37d05e43744b4c3699b234

The only important thing in 244 branch is the mb_ALL-LINKS.user.js file.
And this file is so much different from its master version that there is nothing that can be merged from master for it.

And when 244 branch version of this file will be ready, I will merge 244 branch to master, ignoring all files except ALL LINKS.

The ESLint, editor, project, workflow files are just gadgets I wanted to try. No need to try adding them in 244 branch. 

Sorry sorry @Freso. 🙇 
Please still keep submitting pull requests. 
I love that.

I keep it open, maybe I'll merge it though, as a last merge to this branch, as it may not harm, except adding some unrelated commits in the branch log.
I will first check the changes in my PC.

**Comment by jesus2099** [comment]
Sorry to decline this but that _All Shook Up Links_ branch is really just a one file branch. 
No need to care about the other files that this PR is updating, as all other files than **mb_ALL-LINKS.user.js** will be ignored when I merge this file/branch to master.
🙇‍♀️ 🙇

**Pull request closed without merging**
