### PR TITLE
handle multiple tables of collections

### PR DESCRIPTION
**Pull request by bricas**
My collections page has two sets of table (Event Collections and Release Collections). With the existing script, only the Event Collections got the Load, etc buttons.

I've added a simple loop to add the buttons to each table.

### CODE REVIEW

**Comment by jesus2099** [comment]
I have never thought anything else than release context, does it highlight events ?
It might not, just releases, release-groups, recordings, artists, works and labels, actually…
Hey you don’t have any data in [your event collections](https://musicbrainz.org/user/bricas/collections) actually.
I see the problem… anyway events are not managed so it should only display in front of release collections only, right ? Not all…
Your fix might be the quickest change but will certainly trigger crashes if one clicks LOAD for event collection, no ? :)

**Comment by jesus2099** [comment]
I will try it ! :)

**Comment by jesus2099** [comment]
OK it’s just a quick fix as the settings are inoperent and it looks it could be better graphically.
I will merge this quick fix and make a ticket to enhance it further. :)
Thanks very much.
I didn’t know we could have other types of collections.

**Comment by bricas** [comment]
Thanks for the quick merge! I was only concerning myself with the fact that the other table wasn't being detected and didn't even think about "events" (which I don't use anyway).

**Comment by jesus2099** [comment]
You’re welcome…
Now I remember those event collections appeared long time ago.
Maybe my collection highlighter script was created after I had deleted them.

**Pull request merged**
