### PR TITLE
Auto-detect languages from navigator/MusicBrainz

### PR DESCRIPTION
**Pull request by y-van-z**
Small improvements on the wikidata languages functionality.

- Add meta language keys "navigator" and "musicbrainz"
- "navigator" is replaced by navigator settings (when available)
- "musicbrainz" is replaced by MusicBrainz UI language (while it is harder to retrieve known languages from MusicBrainz user profile)
- Set default languages to ["navigator", "musicbrainz"]

Language detection is put in a separate function (parseLanguages) for later use with other links.

### CODE REVIEW

**Comment by jesus2099** [comment]
Hi @y-van-z, your change is very welcome as I wanted to do that (but only found some [503 error](/jesus2099/konami-command/issues/148#issuecomment-190057994) solution).
So you mean it’s possible to do without server‐side code?
I’m glad, I will check your code out the sooner as possible! :smiley:

**Comment by y-van-z** [comment]
Server-side code is still a workaround for browsers than do not implement "navigator.languages" yet. "navigator.languages" is implemented in Firefox 32, Chrome 37 and Opera 24 [since 2014/09/09](http://gu.illau.me/posts/follow-up-on-navigator-languages/). Other browsers do not have an equivalent functionality for now. For those, the first language setting is used as a [fallback](http://gu.illau.me/posts/the-problem-of-user-language-lists-in-javascript/#how-to-fix-it) and split if necessary (because there is no "en-US" wikipedia, but there is a "zh-min-nan" one).

The proposed default settings is to use the navigator language and the language user selected for MusicBrainz UI. It is roughly equivalent to have native language first and MusicBrainz editing language second. Lucky Firefox/Chrome/Opera users additionally have all their browser languages settings used.

The most pertaining solution would be to use the known languages from MusicBrainz user profile, but these language codes are (1) not ISO 639 and (2) only exposed in the profile editing form.

**Comment by jesus2099** [comment]
Thanks so much, @y-van-z!  :clap: :joy:

**Comment by y-van-z** [comment]
Thank you for the review and additional improvements!

**Pull request merged**
