### PR TITLE
All entity types links

### PR DESCRIPTION
**Pull request by y-van-z**
Implement feature request #187: Enable mb ALL LINKS for all MB entities (except collections).
Collateral fixes include:
- Remove a bit of obsolete code, reduce global variables usage, fix favicon guess timeout function.
- Display autolinks whatever the status of hidden links web service request. Note that hidden links are incidentally displayed below autolinks.

Edit: separate commits make easier to distinguish code moves from other code changes.

### CODE REVIEW

**Comment by jesus2099** [comment]
Thanks @y-van-z, this is a great PR and commit split so that I can understand everything.
A very good lesson for my own future PR. :)

Everything suits me except one thing.
I think I need `%artist-name%`, `%release-name%`, `%work-name%`, etc. not only `%entity-name%` (and `%artist-name%` incidentally).
This way, autolinks will be correctly chosen. On a release page, as `%work-name%` will be unknown, and work autolinks won’t be computed.
If we only have `%entity-name%` will would see many awkard autolinks (work search on artist name, etc.).

What do you think?

Thanks again, so very much!

**Comment by y-van-z** [comment]
In fact, it is already there, see lines [92](https://github.com/y-van-z/konami-command/blob/24114eaf1b1ac5c476ea42b14807e869c7cba3c3/mb_ALL-LINKS.user.js#L92), and [344](https://github.com/y-van-z/konami-command/blob/24114eaf1b1ac5c476ea42b14807e869c7cba3c3/mb_ALL-LINKS.user.js#L344). :honey_pot: 
See also the release example in the prompt of “configure user autolinks”.

**Comment by jesus2099** [comment]
:scream: OMG WOW!!
You have already thought about everything, it’s fabulous!! :heart_eyes:

**Comment by jesus2099** [comment]
Sorry @y-van-z it’s only now that I have a few minutes left to test your PR.

- When I go to [DAVID BOWIE](//musicbrainz.org/artist/5441c29d-3602-4898-b1a1-b77fa23b8e50) with my latest version, pencils and begin dates for en.wikipedia and 2× YouTube links are correctly aligned.
- When I go same place with this PR, those pencil icons and begin dates are shifted up inside the wikidata→wikipedia links… It’s probably because of my wrong method for retrieving links. It seems we come up in some situation worse than #177.

I’m sorry being late because you already are further steps ahead of this PR…

**Comment by y-van-z** [comment]
Hopefully, this bug disappears in the [most advanced branch](https://github.com/y-van-z/konami-command/commits/all-shook-up-links/mb_ALL-LINKS.user.js) that simply drops the faulty code.

**Comment by jesus2099** [comment]
OK, I will live with having the hidden links below the autolinks for some time, but I have fixed the 2 other hindrances:

- hidden links became semi transparent
- dates and pencil icon [shift problem](#issuecomment-225451735) (not #177)

**Comment by jesus2099** [comment]
Thanks again @y-van-z.
Note that I have also changed the WD→WP language settings text shorter to fix a mouse problem, please check this new `master` version with your ongoing `all-shook-up` branch. :)

**Pull request merged**
