### PR TITLE
All shook up links

### PR DESCRIPTION
**Pull request by yvanzo**
Move to multilingual hierarchical search links.

Regression: Asian search links are missing.

### CODE REVIEW

**Comment by y-van-z** [comment]
@jesus2099: I resolved conflicts with `master` recent changes [as you requested](https://github.com/jesus2099/konami-command/pull/238#issuecomment-225874551). You only have to [recreate all Asian search links](https://github.com/jesus2099/konami-command/issues/206#issuecomment-225452797) in the new hierarchy, and everything should be back to normal. The new hierarchical structure is undocumented but pretty self-explanatory and [you already seem to be after it](https://github.com/jesus2099/konami-command/issues/45#issuecomment-225875887).

**Comment by jesus2099** [comment]
Thanks, I will branch this PR and try to re–add my stuff there, as soon as possible. :)

**Comment by jesus2099** [comment]
I’m amazed how you could understand and use my code.
It seems you understood it better than I am able to understand all your new stuff!  ;)

**Comment by jesus2099** [comment]
I have started the branch here. I will like to recover three things:

- [ ] all my searches (I see you renamed autoruns to search, it may sound more intuitive indeed)
- [ ] `POST` searches (some sites simply require it and some searches rely on it for charset switching, like the currently available Encyclopédisque)
- [ ] latin name for non‐latin artists

**Comment by y-van-z** [comment]
> Thanks, I will branch this PR and try to re–add my stuff there, as soon as possible. :)
> I’m amazed how you could understand and use my code.
> It seems you understood it better than I am able to understand all your new stuff!  ;)

You are very welcome. This is a more abrupt set of changes than the previous PR, because it modifies the links/sections structure the rest of your code relied on. That is why it might require a bit more time to understand it. I hope I did not write obfuscated code though!

The parts of your code I am unsure I really understood is the charset sorcery, and more particularly the too many parameters of the `addExternalLinks` function. It was a very large function which mixed many specific cases (add WP links, add section titles, add hidden links, add autolinks) based on too many obscure parameters flowing around. I really hope we can get rid of it in the end. I also would like to cut the new `addSearchLinksSection` function into smaller pieces to not have this hideous thing again. On the other hand, there is a bit of code duplication in `addUserLinks` that will have to be refactored.

> all my searches (I see you renamed autoruns to search, it may sound more intuitive indeed)

Yes, I wanted it to be more comprehensive and to better integrate the MB website, so I used the same wording (_My links_ section is inspired from the _My data_ top menu; _Search links_ is inspired from the _Search_ second-level menu and its two first entries; _Search the whitelist_ refers to the term _whitelist_ in the URL relationships documentation) and the same capitalization as other sidebar sections.

Moreover, using the MB wording helps for translation. I just added the MB supported translations for now, but it would be very nice to have more language targets (based on MB users language statistics) for section title translation, such as :jp: Japanese, for example :innocent: .

> `POST` searches (some sites simply require it and some searches rely on it for charset switching, like the currently available Encyclopédisque)

Does the `%artist-latin-script-name%` token help instead?

As I wrote it above, I am really unsure about the charset issue, I did not completely investigated it.
- Some websites have poor to zero support of different charsets, such as the SACEM repertoire website. Maybe `%artist-latin-script-name%`-based URL should be the priority target for this case. The `%artist-name%`-based second target would be ignored then.
- Other websites have an acceptable support of charsets, such as the ISNI website. Maybe `%artist-name%`-based target is sufficient for this case.

> latin name alternative search for non‐latin artists

This might be a more advanced feature for later on. Along the same lines, I would like to auto-generate search links for related entities. For example, show `%work-name%`-based search links on a recording page, since recordings are most often named after works. But this is for later on! :calendar:

**Comment by jesus2099** [comment]
@y-van-z, are tokens search/replaced in search labels too already?
It was not in my code but that’s something I wanted to add so I just ask here and then I will add this feature in the branch if it is not. :)

**Comment by y-van-z** [comment]
No, they are just localized. But you can easily do it by calling the `replaceAllTokens` function.

**Comment by jesus2099** [comment]
Thanks, that’s great, indeed. :)

**Comment by jesus2099** [comment]
Mosul->module

**Comment by jesus2099** [comment]
Here is what I have done so far, I am still not giving up.
https://github.com/jesus2099/konami-command/commits/%23244_y-van-z_all-shook-up-links/mb_ALL-LINKS.user.js

**Comment by jesus2099** [comment]
I must include my #335 fix, if necessary in this branch.

**Comment by jesus2099** [comment]
And #293.

**Comment by jesus2099** [comment]
How did I close that?!

**Comment by jesus2099** [comment]
@yvanzo I cannot reopen this and I don't know why it closed on my behalf.
It seems that you still have your https://github.com/yvanzo/konami-command/tree/all-shook-up-links available
Could you resubmit your PR?
I loose all my edits on this branch? 😱 https://github.com/jesus2099/konami-command/pull/244/commits
It's really strange what happened. I left it open too long.

**Comment by jesus2099** [comment]
My branch is still there https://github.com/jesus2099/konami-command/commits/%23244_y-van-z_all-shook-up-links so I could theoretically retrieve my fixes to your PR but it's quite depressing. :/

**Comment by yvanzo** [comment]
Sorry I did not see the above messages at that time, but I cannot reopen this PR either.

**Pull request closed without merging**
