### PR TITLE
Use some JSHint rules

### PR DESCRIPTION
**Pull request by Martii**
Applies to OpenUserJS/OpenUserJS.org#720

NOTES:
* This is either new or I completely missed this back then. Enjoy! :)
* Some white space automatically removed from the source with my editor

### CODE REVIEW

**Comment by Martii** [comment]
Btw `self` doesn't seem to be defined in the `@require`... Most likely it's not picking up on the assumed [`window.self`](https://developer.mozilla.org/docs/Web/API/Window/self) ? Be careful what you "shut off" as it could be important down the line for "code correctness" *(as they say)*. I placed it near the `@require` since it will be a reminder of what's "exported" to the global space for your script. You can use these, and more than once, anywhere in your Userscript.

**Comment by jesus2099** [comment]
Thank you @Martii. :)
What do you mean what I *shut off*? I did not understand that part.

**Comment by Martii** [comment]
With JSHint it has ways of turning on or off the syntax checking *(the triangle)* e.g. making a script seem better or worse. I tried doing some of these on our end just as a test and it got much worse... then I had to fix that with another one. So it could snowball into a mess. The ones in this PR are mostly harmless although I did want to go back and revisit the `self`. The original fork I had to delete and it is going to take a lot more to pull in this PR into the new fork so I can make changes. I won't be disappointed if you just do this yourself and close this but I discovered a "new toy" with JSHint and it reminded me of your issue. The original assessment of treating the triangles as advisories but not necessarily definitive is still in place though.

**Comment by Martii** [comment]
The `self` message will disappear if the entire script is encapsulated in an [IIFE](https://developer.mozilla.org/docs/Glossary/IIFE). JSHint also now recommends that `"use strict"` should be in that type of function to prevent possible collision with libraries that are "appended" to the top level script. e.g. `@require`s. If you were around when [`@unwrap`](https://sourceforge.net/p/greasemonkey/wiki/Metadata_Block/#unwrap) was in effect GM itself used to IIFE things but allegedly they don't anymore since after 0.9.22.

I'm going to go ahead and close this, as it is incorrect depending on what you want to do, but that's some more intel for you if you wish to quiet some of those triangles. :)

**Comment by Martii** [comment]
Here you go. Hopefully a lot more clear. :smiley: 

See also:
* https://openuserjs.org/about/Frequently-Asked-Questions#q-why-does-my-script-source-have-so-many-warning-triangle-notices-

**Pull request closed without merging**
