### PR TITLE
FIX #231 : fix languages preview and duplicates

### LINKED ISSUE #231: navigator.languages regression
I copy @y-van-z’s [remark](../commit/f3f2ef5e48fec81eadf6fce8da7d7f78ef481a1d#diff-8a6e63ef5b5a21e5b708df53d9731b9aR612) here:

> 1. The above line introduces duplicates when the `outputLanguages` array already contains the two-letters language code.
> Example: `["pt-BR", "pt"]` → `["pt-BR", "pt", "pt"]`
>
> 2. It does not deal very well with the `["zh-min-nan"]` locale.
> Example: `["zh-min-nan"]` → `["zh-min-nan", "zh", "zh"]`
>
> 3. Since it is done out of the `guessNavigatorLanguages` function, it can not be previewed from the prompt.

### PR DESCRIPTION
**Pull request by y-van-z**
FIX #231 : fix languages preview and duplicates

Additionally preview expanded/split/deduplicated languages.

### CODE REVIEW

**Comment by jesus2099** [comment]
I am not sure but it looks like you have removed the thing that was preventing duplicate languages:

    if (outputLanguages.indexOf(nextLanguage) < 0) {
        /* append nextLanguage to the list */
    }

I am not on a user script PC today but I will try to reproduce #231 again, with your advices there. :)

**Comment by y-van-z** [comment]
I did not remove it, I just deduplicated the deduplication code! It now runs at the end of `parseLanguages` function only rather than at various disparate places. The code at the end of `parseLanguages` is just a fixed version of the previous `splitLanguages` function code.

**Comment by jesus2099** [comment]
Hey @y-van-z, I’ve noticed the said improvement when trying in Firefox with en-GB in my language list (`navigator.languages`).

- Before PR: `"en-GB", "en", "en"` 
- After PR: `"en-GB", "en"` 

Do you think it’s OK to merge this before #238 or do you prefer waiting and merging in correct sequence?

**Comment by y-van-z** [comment]
It is OK to merge this now, as these changes are completely independent from other branches.

**Pull request merged**
